### ISSUE TITLE
CSS logisch indelen

### ISSUE THREAD

**Issue by joostf** [MiloZwemmer/99verhalen#4]
Begin bijvoorbeeld met het stijlen van de body, dit is ook het eerste element dat je tegenkomt in de html

https://github.com/MiloZwemmer/99verhalen/blob/master/index.css#L30

**Comment by MiloZwemmer** [comment]
Css volgorde veranderd en comments toegevoegd binnen de css. Body staat nu bovenaan gevolgd door de header.
